In [1]:
import numpy as np
import pandas as pd


In [2]:
arr1=np.empty(4)
arr1

array([2.12199579e-314, 4.67296746e-307, 6.52166653e-321, 9.50654115e-312])

In [3]:
list=[1,2,3,4,5]
arr1=np.array(list)

In [4]:
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr1=np.zeros(5)

In [6]:
arr1

array([0., 0., 0., 0., 0.])

In [7]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
a=np.random.rand(5)
a

array([0.92217779, 0.46341551, 0.6567773 , 0.84453708, 0.20730389])

In [11]:
arr=np.array([[1,2,3],[3,4,5]])
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
arr=np.array([[[1,2,3],[4,5,6],[1,2,3]],
              [[1,1,2],[3,2,1],[2,3,4]]])
              


In [14]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3]],

       [[1, 1, 2],
        [3, 2, 1],
        [2, 3, 4]]])

In [15]:
arr1=np.array([[[1,2,3],[1,2,3],[1,2,3]],
               [[1,2,3],[4,5,6],[3,4,5]]])

In [16]:
arr1

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [4, 5, 6],
        [3, 4, 5]]])

In [23]:

arr1=np.ones((2,4),dtype=int)

arr2=np.ones((2,3,4),dtype=int)

2-D array
3-D array


In [25]:
print('2-D array')
arr1
print('3-D array')
arr2

2-D array
3-D array


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [26]:
arr1=np.full((2,3,4),5)

In [27]:
arr1

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [32]:
arr3=np.empty((2,2,2))

In [33]:
arr3

array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 1.19366260e-320],
        [3.11525958e-307, 1.24610723e-306]]])

In [34]:
arr1=np.array([[1,2,3],[5,6,7]])
arr1

array([[1, 2, 3],
       [5, 6, 7]])

In [36]:
arr1[1,0]=20

In [37]:
arr1

array([[ 1,  2,  3],
       [20,  6,  7]])

In [38]:
arr=np.array([[[1,2,3],[4,5,6],[1,2,3]],
              [[1,1,2],[3,2,1],[2,3,4]]])
              

In [39]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3]],

       [[1, 1, 2],
        [3, 2, 1],
        [2, 3, 4]]])

In [42]:
arr[0,1,2]
arr[0,0,2]

3

In [43]:
r=int(input("enter no of rows:"))
c=int(input("enter no of columns:"))
arr=np.ones((r,c),dtype=int)
for i in range(r):
  for j in range(c):
    values=int(input("enter values to insert into yhe matrix:"))
    arr[i][j]=values
print(arr)    

[[1 2 2]
 [3 4 5]
 [6 7 1]]


In [49]:
r=int(input("enter no of rows:"))
c=int(input("enter no of columns:"))
arr=np.ones((r,c),dtype=int)
print(arr)
for i in range(r):
  for j in range(c):
    values=int(input("enter the values to be inserted into the matrix:"))
    arr[i][j]=values
print(arr)    

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[ 1  2  1  2  3]
 [ 4  5  6  5  4]
 [ 3  7  6 55 44]
 [33 43 54 65 87]]


In [50]:
arr=np.array([1,2,3,4,50])
revarr=arr[::-1]
revarr

array([50,  4,  3,  2,  1])

In [53]:
array1 = np.array([   [1, 3, 5, 7], 
                      [9, 11, 13, 15],
                      [2, 4, 6, 8]])
arr=array1[0:2,0:2]

In [54]:
arr

array([[ 1,  3],
       [ 9, 11]])

In [55]:
list=[1,2,3,4,5,6,7,8,9]
arr=np.reshape(list,(3,3))

In [56]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])